'''
Error handling is a way to handle the exception that is generated by our program those exception that are
unexpected to occur. using try and except we can handle the exceptions.. there are multiple types of exception that can be used according to the excepted type of execption... such as :
1.ZeroDivisionError
2.ValueError
3.NameError
Etc...
'''
while True:
    try:
        num = int(input("what is your age ? :"))
        print(f"Ohh you are {num}")
    except ValueError: 
        print("please enter a number") 
    except ZeroDivisionError:
        print("Age can not be zero")
    else: # if there will no exception in the code then this else block will be executed...
        break;